---
plugin: amazon.aws.aws_ec2

regions:
  - us-east-1

keyed_groups:
  - key: tags.Role
    seperator: ""
  - key: tags.BaseDN
    seperator: ""
  - key: tags.Hostname
    seperator: ""

# removes leading "_" note value _meta is a system value not tagged on any instances
# requires ansible version>=2.11
leading_separator: "no"

cache: "yes"

filters:
  tag:BaseDN: "devnet13.edge.othentic.private"

hostnames:
  - instance-id
